# Generated by Django 6.0.4 on 2026-05-01 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=50, verbose_name='Código do Ativo')),
                ('issuer', models.CharField(max_length=100, verbose_name='Emissor do Título')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Operação')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
